name: "frontend"

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
  push:
    branches:
      - "main"
    paths:
      - "./frontend/src/*.js"
      - "./frontend/components/**/*.vue"
      - "./frontend/pages/**/*.vue"
      - ".github/workflows/frontend.yml"
  pull_request:
    types: [synchronize, opened, reopened]
    paths:
      - "./frontend/src/*.js"
      - "./frontend/components/**/*.vue"
      - "./frontend/pages/**/*.vue"
      - ".github/workflows/frontend.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn test
